name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: execute py script
        run: python Hello_world.py

      - name: Deploy code to Lambda
          uses: qubitro/action-lambda-python-zip@v1.0
          with:
            lambda_layer_arn: 'arn:aws:lambda:us-east-1:681164186076:layer:layer-name'
            lambda_function_name: HelloWorld
            lambda_region: 'us-east-1'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}